In [1]:
l=[]
for i in range(5):
    x=int(input("enter an integer"))
    l.append(x)

print(max(l))
print(min(l))
print(sum(l))

ValueError: invalid literal for int() with base 10: 'l'

In [1]:
d={"a":1, "b":2}
for x in d:
    print(x)

a
b

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("GlobalWeatherRepository - GlobalWeatherRepository.csv")

In [ ]:
a=[10,20,30,40,50]
i=1
whilei<len(a)

In [ ]:
a=[1,2,3,4,5,6]
for x in a:
    print(x)

1
2
3
4
5
6

In [ ]:
a=[1,3,4,4,4,5,6]
set(a)

{1, 3, 4, 5, 6}

In [ ]:
a=[200,300,400]
print(a.index(300))
print(a.index(400))
print(a.index(200))

1
2
0

In [ ]:
a=[2,4,3,7,9]
a.clear()
print(a)

[]

In [ ]:
a=[1,2,3]
a.reverse()
print(a)

[3, 2, 1]

In [ ]:
a=[6,3,9,1]
print(len(a))
print(max(a))
print(min(a))
print(sum(a))
print(sorted(a))

4
9
1
19
[1, 3, 6, 9]

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("GlobalWeatherRepository - GlobalWeatherRepository.csv")

In [6]:
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50,18:50,12:12,01:11,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21,19:54,12:58,02:14,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40,19:50,13:15,02:14,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31,21:11,14:12,03:31,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12,17:55,13:17,00:38,Waxing Gibbous,55

In [7]:
df.tail()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30,19.1,66.3,Partly Cloudy,...,16.35,18.15,2,2,06:18,18:38,02:36,14:31,Waning Crescent,31
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30,34.2,93.6,Sunny,...,61.15,64.45,3,8,05:41,18:14,02:02,13:21,Waning Crescent,35
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30,19.3,66.7,Sunny,...,7.45,15.35,1,1,05:51,18:17,02:06,13:45,Waning Crescent,34
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30,18.5,65.3,Sunny,...,5.45,6.15,1,1,06:14,18:01,01:26,14:30,Waning Crescent,33
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30,17.4,63.3,Sunny,...,19.85,20.55,2,2,06:04,17:49,01:10,14:22,Waning Crescent,33

In [8]:
df.sample(8)

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
92286,Mongolia,Ulaanbaatar,47.9167,106.9167,Asia/Ulaanbaatar,1756886400,2025-09-03 16:00,21.2,70.2,Sunny,...,8.695,9.250,1,1,06:13,19:30,17:35,00:11,Waxing Gibbous,73
68391,Tunisia,Tunis,36.8028,10.1797,Africa/Tunis,1746262800,2025-05-03 10:00,25.0,77.0,Sunny,...,15.170,26.825,1,2,05:23,19:10,10:21,00:44,Waxing Crescent,33
81592,Romania,Bucharest,44.4333,26.1000,Europe/Bucharest,1752137100,2025-07-10 11:45,24.3,75.7,Sunny,...,5.735,8.140,1,1,05:41,21:01,21:18,04:35,Full Moon,99
49220,Mauritius,Port Louis,-20.1619,57.4989,Indian/Mauritius,1737800100,2025-01-25 14:15,31.1,88.0,Partly cloudy,...,9.620,14.430,1,1,05:50,18:55,01:36,15:31,Waning Crescent,23
115801,Comoros,Moroni,-11.7042,43.2403,Indian/Comoro,1767338100,2026-01-02 10:15,25.5,78.0,Light rain shower,...,5.750,7.450,1,1,05:47,18:35,17:49,04:20,Waxing Gibbous,96
66185,Mozambique,Maputo,-25.9653,32.5892,Africa/Maputo,1745312400,2025-04-22 11:00,29.0,84.2,Sunny,...,16.280,19.240,2,2,06:09,17:28,00:11,13:56,Waning Crescent,41
31459,Botswana,Gaborone,-24.6464,25.9119,Africa/Gaborone,1729934100,2024-10-26 11:15,34.4,93.9,Sunny,...,23.310,34.410,2,2,05:33,18:28,02:14,13:31,Waning Crescent,34
6226,Uzbekistan,Tashkent,41.3200,69.2500,Asia/Tashkent,1718460000,2024-06-15 19:00,32.9,91.3,Sunny,...,13.400,16.100,1,2,04:49,19:58,13:22,00:55,Waxing Gibbous,57

In [9]:
df.shape

(135073, 41)

In [10]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='object')

In [11]:
df.info

<bound method DataFrame.info of             country     location_name  latitude  longitude         timezone  \
0       Afghanistan             Kabul   34.5200    69.1800       Asia/Kabul
1           Albania            Tirana   41.3300    19.8200    Europe/Tirane
2           Algeria           Algiers   36.7600     3.0500   Africa/Algiers
3           Andorra  Andorra La Vella   42.5000     1.5200   Europe/Andorra
4            Angola            Luanda   -8.8400    13.2300    Africa/Luanda
...             ...               ...       ...        ...              ...
135068    Venezuela           Caracas   10.5000   -66.9167  America/Caracas
135069      Vietnam             Hanoi   21.0333   105.8500     Asia/Bangkok
135070        Yemen             Sanaa   15.3547    44.2067        Asia/Aden
135071       Zambia            Lusaka  -15.4167    28.2833    Africa/Lusaka
135072     Zimbabwe            Harare  -17.8178    31.0447    Africa/Harare

        last_updated_epoch      last_updated  temperature_celsius  \
0               1715849100  2024-05-16 13:15                 26.6
1               1715849100  2024-05-16 10:45                 19.0
2               1715849100  2024-05-16 09:45                 23.0
3               1715849100  2024-05-16 10:45                  6.3
4               1715849100  2024-05-16 09:45                 26.0
...                    ...               ...                  ...
135068          1775975400  2026-04-12 02:30                 19.1
135069          1775975400  2026-04-12 13:30                 34.2
135070          1775975400  2026-04-12 09:30                 19.3
135071          1775975400  2026-04-12 08:30                 18.5
135072          1775975400  2026-04-12 08:30                 17.4

        temperature_fahrenheit condition_text  ...  air_quality_PM2.5  \
0                         79.8  Partly Cloudy  ...               8.40
1                         66.2  Partly cloudy  ...               1.10
2                         73.4          Sunny  ...              10.40
3                         43.3  Light drizzle  ...               0.70
4                         78.8  Partly cloudy  ...             183.40
...                        ...            ...  ...                ...
135068                    66.3  Partly Cloudy  ...              16.35
135069                    93.6          Sunny  ...              61.15
135070                    66.7          Sunny  ...               7.45
135071                    65.3          Sunny  ...               5.45
135072                    63.3          Sunny  ...              19.85

        air_quality_PM10  air_quality_us-epa-index air_quality_gb-defra-index  \
0                  26.60                         1                          1
1                   2.00                         1                          1
2                  18.40                         1                          1
3                   0.90                         1                          1
4                 262.30                         5                         10
...                  ...                       ...                        ...
135068             18.15                         2                          2
135069             64.45                         3                          8
135070             15.35                         1                          1
135071              6.15                         1                          1
135072             20.55                         2                          2

        sunrise  sunset  moonrise  moonset       moon_phase  moon_illumination
0         04:50   18:50     12:12    01:11   Waxing Gibbous                 55
1         05:21   19:54     12:58    02:14   Waxing Gibbous                 55
2         05:40   19:50     13:15    02:14   Waxing Gibbous                 55
3         06:31   21:11     14:12    03:31   Waxing Gibbous                 55
4         06:12   17:55     13:17    00:38   Waxing Gibbous                 55
...         ...     ...       ...      ...              ...                ...
135068    06:18   18:38     02:36    14:31  Waning Crescent                 31
135069    05:41   18:14     02:02    13:21  Waning Crescent                 35
135070    05:51   18:17     02:06    13:45  Waning Crescent                 34
135071    06:14   18:01     01:26    14:30  Waning Crescent                 33
135072    06:04   17:49     01:10    14:22  Waning Crescent                 33

[135073 rows x 41 columns]>

In [12]:
df.dtypes

country                          object
location_name                    object
latitude                        float64
longitude                       float64
timezone                         object
last_updated_epoch                int64
last_updated                     object
temperature_celsius             float64
temperature_fahrenheit          float64
condition_text                   object
wind_mph                        float64
wind_kph                        float64
wind_degree                       int64
wind_direction                   object
pressure_mb                       int64
pressure_in                     float64
precip_mm                       float64
precip_in                       float64
humidity                          int64
cloud                             int64
feels_like_celsius              float64
feels_like_fahrenheit           float64
visibility_km                   float64
visibility_miles                  int64
uv_index                        float64
gust_mph                        float64
gust_kph                        float64
air_quality_Carbon_Monoxide     float64
air_quality_Ozone               float64
air_quality_Nitrogen_dioxide    float64
air_quality_Sulphur_dioxide     float64
air_quality_PM2.5               float64
air_quality_PM10                float64
air_quality_us-epa-index          int64
air_quality_gb-defra-index        int64
sunrise                          object
sunset                           object
moonrise                         object
moonset                          object
moon_phase                       object
moon_illumination                 int64
dtype: object

In [16]:
  df["country"]

0         Afghanistan
1             Albania
2             Algeria
3             Andorra
4              Angola
             ...
135068      Venezuela
135069        Vietnam
135070          Yemen
135071         Zambia
135072       Zimbabwe
Name: country, Length: 135073, dtype: object

In [19]:
df.iloc[5:10]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
5,Antigua and Barbuda,Saint John's,17.12,-61.85,America/Antigua,1715849100,2024-05-16 04:45,26.0,78.8,Partly cloudy,...,1.2,4.5,1,1,05:36,18:32,13:05,01:14,Waxing Gibbous,55
6,Argentina,Buenos Aires,-34.59,-58.67,America/Argentina/Buenos_Aires,1715849100,2024-05-16 05:45,8.0,46.4,Clear,...,4.0,5.3,1,1,07:43,17:59,14:36,01:04,Waxing Gibbous,55
7,Armenia,Yerevan,40.18,44.51,Asia/Yerevan,1715849100,2024-05-16 12:45,19.0,66.2,Partly cloudy,...,0.8,0.9,1,1,05:45,20:12,13:17,02:31,Waxing Gibbous,55
8,Australia,Canberra,-35.28,149.22,Australia/Sydney,1715849100,2024-05-16 18:45,9.0,48.2,Clear,...,3.7,5.4,1,1,06:52,17:07,13:31,No moonset,Waxing Gibbous,55
9,Austria,Vienna,48.20,16.37,Europe/Vienna,1715849100,2024-05-16 10:45,16.0,60.8,Partly cloudy,...,3.7,4.4,1,1,05:14,20:29,13:00,02:42,Waxing Gibbous,55

In [20]:
df[df["latitude"]>50]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
15,Belarus,Minsk,53.9000,27.5700,Europe/Minsk,1715849100,2024-05-16 11:45,17.0,62.6,Sunny,...,1.60,1.70,1,1,05:05,21:08,12:59,03:13,Waxing Gibbous,55
16,Belgium,Brussels,50.8300,4.3300,Europe/Brussels,1715849100,2024-05-16 10:45,15.0,59.0,Partly cloudy,...,14.70,15.80,1,2,05:52,21:28,13:45,03:38,Waxing Gibbous,55
44,Czech Republic,Prague,50.0800,14.4700,Europe/Prague,1715849100,2024-05-16 10:45,18.0,64.4,Sunny,...,3.40,3.90,1,1,05:14,20:44,13:04,02:55,Waxing Gibbous,55
46,Denmark,Copenhagen,55.6700,12.5800,Europe/Copenhagen,1715849100,2024-05-16 10:45,16.0,60.8,Sunny,...,5.80,6.90,1,1,04:56,21:17,12:58,03:19,Waxing Gibbous,55
55,Estonia,Tallinn,59.4300,24.7300,Europe/Tallinn,1715849100,2024-05-16 11:45,19.0,66.2,Sunny,...,7.30,7.60,1,1,04:44,21:52,12:54,03:45,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135017,Poland,Warsaw,52.2500,21.0000,Europe/Warsaw,1775975400,2026-04-12 08:30,6.1,43.0,Sunny,...,12.85,14.95,1,2,05:46,19:29,04:07,13:04,Waning Crescent,33
135021,Russia,Moscow,55.7522,37.6156,Europe/Moscow,1775975400,2026-04-12 09:30,5.2,41.4,Partly cloudy,...,36.45,48.95,2,4,05:33,19:30,04:16,12:39,Waning Crescent,34
135046,Sweden,Stockholm,59.3333,18.0500,Europe/Stockholm,1775975400,2026-04-12 08:30,5.4,41.7,Sunny,...,4.55,5.55,1,1,05:42,19:57,04:55,12:43,Waning Crescent,33
135061,Ukraine,Kyiv,50.4333,30.5167,Europe/Kyiv,1775975400,2026-04-12 09:30,4.3,39.8,Partly Cloudy,...,13.65,15.25,1,2,06:11,19:48,04:21,13:31,Waning Crescent,34
135063,United Kingdom,London,51.5171,-0.1062,Europe/London,1775975400,2026-04-12 07:30,8.0,46.4,Sunny,...,5.05,15.15,1,1,06:11,19:52,04:29,13:36,Waning Crescent,33

In [21]:
df["latitude"]>50

0         False
1         False
2         False
3         False
4         False
          ...
135068    False
135069    False
135070    False
135071    False
135072    False
Name: latitude, Length: 135073, dtype: bool

In [22]:
len(df[df["latitude"]>50])

13835

In [24]:
df[(df["latitude"]>50) & (df["latitude"]<100)]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
15,Belarus,Minsk,53.9000,27.5700,Europe/Minsk,1715849100,2024-05-16 11:45,17.0,62.6,Sunny,...,1.60,1.70,1,1,05:05,21:08,12:59,03:13,Waxing Gibbous,55
16,Belgium,Brussels,50.8300,4.3300,Europe/Brussels,1715849100,2024-05-16 10:45,15.0,59.0,Partly cloudy,...,14.70,15.80,1,2,05:52,21:28,13:45,03:38,Waxing Gibbous,55
44,Czech Republic,Prague,50.0800,14.4700,Europe/Prague,1715849100,2024-05-16 10:45,18.0,64.4,Sunny,...,3.40,3.90,1,1,05:14,20:44,13:04,02:55,Waxing Gibbous,55
46,Denmark,Copenhagen,55.6700,12.5800,Europe/Copenhagen,1715849100,2024-05-16 10:45,16.0,60.8,Sunny,...,5.80,6.90,1,1,04:56,21:17,12:58,03:19,Waxing Gibbous,55
55,Estonia,Tallinn,59.4300,24.7300,Europe/Tallinn,1715849100,2024-05-16 11:45,19.0,66.2,Sunny,...,7.30,7.60,1,1,04:44,21:52,12:54,03:45,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135017,Poland,Warsaw,52.2500,21.0000,Europe/Warsaw,1775975400,2026-04-12 08:30,6.1,43.0,Sunny,...,12.85,14.95,1,2,05:46,19:29,04:07,13:04,Waning Crescent,33
135021,Russia,Moscow,55.7522,37.6156,Europe/Moscow,1775975400,2026-04-12 09:30,5.2,41.4,Partly cloudy,...,36.45,48.95,2,4,05:33,19:30,04:16,12:39,Waning Crescent,34
135046,Sweden,Stockholm,59.3333,18.0500,Europe/Stockholm,1775975400,2026-04-12 08:30,5.4,41.7,Sunny,...,4.55,5.55,1,1,05:42,19:57,04:55,12:43,Waning Crescent,33
135061,Ukraine,Kyiv,50.4333,30.5167,Europe/Kyiv,1775975400,2026-04-12 09:30,4.3,39.8,Partly Cloudy,...,13.65,15.25,1,2,06:11,19:48,04:21,13:31,Waning Crescent,34
135063,United Kingdom,London,51.5171,-0.1062,Europe/London,1775975400,2026-04-12 07:30,8.0,46.4,Sunny,...,5.05,15.15,1,1,06:11,19:52,04:29,13:36,Waning Crescent,33

In [ ]:
df[(df["latitude"]>50) | (df["latitude"]<100)]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.40,26.60,1,1,04:50,18:50,12:12,01:11,Waxing Gibbous,55
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.10,2.00,1,1,05:21,19:54,12:58,02:14,Waxing Gibbous,55
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.40,18.40,1,1,05:40,19:50,13:15,02:14,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.70,0.90,1,1,06:31,21:11,14:12,03:31,Waxing Gibbous,55
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.40,262.30,5,10,06:12,17:55,13:17,00:38,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30,19.1,66.3,Partly Cloudy,...,16.35,18.15,2,2,06:18,18:38,02:36,14:31,Waning Crescent,31
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30,34.2,93.6,Sunny,...,61.15,64.45,3,8,05:41,18:14,02:02,13:21,Waning Crescent,35
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30,19.3,66.7,Sunny,...,7.45,15.35,1,1,05:51,18:17,02:06,13:45,Waning Crescent,34
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30,18.5,65.3,Sunny,...,5.45,6.15,1,1,06:14,18:01,01:26,14:30,Waning Crescent,33
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30,17.4,63.3,Sunny,...,19.85,20.55,2,2,06:04,17:49,01:10,14:22,Waning Crescent,33

In [ ]:
df[""]

In [28]:
df[(df)["latitude"]>50 * (df["longitude"]<100)]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
15,Belarus,Minsk,53.9000,27.5700,Europe/Minsk,1715849100,2024-05-16 11:45,17.0,62.6,Sunny,...,1.60,1.70,1,1,05:05,21:08,12:59,03:13,Waxing Gibbous,55
16,Belgium,Brussels,50.8300,4.3300,Europe/Brussels,1715849100,2024-05-16 10:45,15.0,59.0,Partly cloudy,...,14.70,15.80,1,2,05:52,21:28,13:45,03:38,Waxing Gibbous,55
24,Brunei Darussalam,Bandar Seri Begawan,4.8800,114.9300,Asia/Brunei,1715849100,2024-05-16 16:45,32.0,89.6,Patchy light rain with thunder,...,2.20,2.30,1,1,06:06,18:27,13:06,00:54,Waxing Gibbous,55
30,Cambodia,Phnom Penh,11.5500,104.9200,Asia/Phnom_Penh,1715849100,2024-05-16 15:45,38.0,100.4,Partly cloudy,...,17.10,23.00,2,2,05:37,18:17,12:41,00:43,Waxing Gibbous,55
36,China,Beijing,39.9300,116.3900,Asia/Shanghai,1715849100,2024-05-16 16:45,29.0,84.2,Sunny,...,84.90,107.80,4,10,04:58,19:24,12:17,01:39,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135046,Sweden,Stockholm,59.3333,18.0500,Europe/Stockholm,1775975400,2026-04-12 08:30,5.4,41.7,Sunny,...,4.55,5.55,1,1,05:42,19:57,04:55,12:43,Waning Crescent,33
135051,Thailand,Bangkok,13.7500,100.5167,Asia/Bangkok,1775975400,2026-04-12 13:30,38.2,100.8,Sunny,...,19.85,22.15,2,2,06:07,18:31,02:11,13:54,Waning Crescent,35
135061,Ukraine,Kyiv,50.4333,30.5167,Europe/Kyiv,1775975400,2026-04-12 09:30,4.3,39.8,Partly Cloudy,...,13.65,15.25,1,2,06:11,19:48,04:21,13:31,Waning Crescent,34
135063,United Kingdom,London,51.5171,-0.1062,Europe/London,1775975400,2026-04-12 07:30,8.0,46.4,Sunny,...,5.05,15.15,1,1,06:11,19:52,04:29,13:36,Waning Crescent,33
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30,34.2,93.6,Sunny,...,61.15,64.45,3,8,05:41,18:14,02:02,13:21,Waning Crescent,35

In [35]:
df["timezone"].dtype

dtype('O')

In [36]:
df["test"]=df["timezone"]

In [37]:
df["test2"]=df["timezone"].str.split("/")

In [8]:
["latituddfe"].value_counts()

AttributeError: 'list' object has no attribute 'value_counts'

In [6]:
import pandas as pd

In [7]:
df=pd.read_csv("GlobalWeatherRepository - GlobalWeatherRepository.csv")

In [9]:
df["latitude"].value_counts()

latitude
 41.90    833
 40.40    832
 12.15    830
 5.55     695
 3.75     695
         ...
 39.53      1
 4.60       1
 4.05       1
-4.05       1
 59.89      1
Name: count, Length: 397, dtype: int64

In [10]:
df["latitude"].mean()

np.float64(19.208948125087915)

In [11]:
df["latitude"].max()

64.15

In [12]:
df["latitude"].min()

-41.3

In [19]:
df[df["country"]== "China"]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
36,China,Beijing,39.9300,116.3900,Asia/Shanghai,1715849100,2024-05-16 16:45,29.0,84.2,Sunny,...,84.90,107.80,4,10,04:58,19:24,12:17,01:39,Waxing Gibbous,55
231,China,Beijing,39.9300,116.3900,Asia/Shanghai,1715868000,2024-05-16 22:00,23.0,73.4,Clear,...,228.20,302.10,5,10,04:58,19:24,12:17,01:39,Waxing Gibbous,55
426,China,Beijing,39.9300,116.3900,Asia/Shanghai,1715961600,2024-05-18 00:00,24.0,75.2,Clear,...,221.90,265.90,5,10,04:58,19:25,13:18,02:01,Waxing Gibbous,64
618,China,Beijing,39.9300,116.3900,Asia/Shanghai,1716042600,2024-05-18 22:30,24.0,75.2,Clear,...,171.70,196.40,5,10,04:57,19:26,14:17,02:21,Waxing Gibbous,73
812,China,Beijing,39.9300,116.3900,Asia/Shanghai,1716127200,2024-05-19 22:00,20.0,68.0,Clear,...,43.50,52.30,3,5,04:56,19:27,15:17,02:40,Waxing Gibbous,81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134134,China,Beijing,39.9289,116.3883,Asia/Shanghai,1775629800,2026-04-08 14:30,19.3,66.7,Sunny,...,66.05,79.05,4,9,05:48,18:45,00:13,08:56,Waning Gibbous,73
134329,China,Beijing,39.9289,116.3883,Asia/Shanghai,1775716200,2026-04-09 14:30,11.4,52.5,Overcast,...,61.85,69.35,3,8,05:47,18:46,01:05,09:51,Waning Gibbous,64
134524,China,Beijing,39.9289,116.3883,Asia/Shanghai,1775803500,2026-04-10 14:45,28.3,82.9,Sunny,...,75.35,89.55,4,10,05:45,18:47,01:50,10:50,Last Quarter,55
134719,China,Beijing,39.9289,116.3883,Asia/Shanghai,1775889000,2026-04-11 14:30,21.1,70.0,Sunny,...,69.35,119.85,4,9,05:44,18:48,02:27,11:55,Waning Crescent,46
134914,China,Beijing,39.9289,116.3883,Asia/Shanghai,1775975400,2026-04-12 14:30,24.0,75.2,Sunny,...,65.15,79.35,3,9,05:42,18:49,02:59,13:00,Waning Crescent,36

In [22]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [23]:
df.isnull()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
135069,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
135070,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
135071,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
135072,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.sort_values(by="latitude")

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
101262,New Zealand,Wellington,-41.30,174.7833,Pacific/Auckland,1760859900,2025-10-19 20:45,14.1,57.4,Clear,...,7.250,10.050,1,1,06:26,19:47,05:16,17:32,Waning Crescent,9
12891,New Zealand,Wellington,-41.30,174.7800,Pacific/Auckland,1721479500,2024-07-21 00:45,10.4,50.7,Partly cloudy,...,0.900,1.500,1,1,07:40,17:16,15:27,06:48,Waxing Gibbous,97
24760,New Zealand,Wellington,-41.30,174.7800,Pacific/Auckland,1726915500,2024-09-21 22:45,12.3,54.1,Partly cloudy,...,5.735,10.545,1,1,06:12,18:16,22:20,07:34,Waning Gibbous,88
94439,New Zealand,Wellington,-41.30,174.7833,Pacific/Auckland,1757836800,2025-09-14 20:00,10.0,50.0,Partly cloudy,...,2.035,2.405,1,1,06:24,18:09,01:03,09:47,Last Quarter,61
115496,New Zealand,Wellington,-41.30,174.7833,Pacific/Auckland,1767164400,2025-12-31 20:00,16.2,61.2,Overcast,...,5.650,8.350,1,1,05:50,20:57,17:37,02:10,Waxing Gibbous,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128909,Iceland,Reykjavik,64.15,-21.9500,Atlantic/Reykjavik,1773297000,2026-03-12 06:30,-3.2,26.3,Clear,...,1.750,4.050,1,1,07:57,19:20,....,....,Waning Crescent,44
91663,Iceland,Reykjavik,64.15,-21.9500,Atlantic/Reykjavik,1756627200,2025-08-31 08:00,11.2,52.2,Sunny,...,7.215,9.435,1,1,06:08,20:46,00:00,00:00,First Quarter,47
131249,Iceland,Reykjavik,64.15,-21.9500,Atlantic/Reykjavik,1774333800,2026-03-24 06:30,-0.8,30.6,Light snow,...,2.150,4.250,1,1,07:15,19:56,****,****,Waxing Crescent,30
104334,Iceland,Reykjavik,64.15,-21.9500,Atlantic/Reykjavik,1762244100,2025-11-04 08:15,2.0,35.6,Clear,...,3.850,6.350,1,1,09:22,17:00,16:08,07:47,Waxing Gibbous,96
126942,Iceland,Reykjavik,64.15,-21.9500,Atlantic/Reykjavik,1772346600,2026-03-01 06:30,-4.0,24.8,Partly cloudy,...,4.750,6.850,1,1,08:35,18:46,15:37,08:56,Waxing Gibbous,93

In [27]:
df=df.drop_duplicates()

In [28]:
df=df.dropna(subset=["latitude"])

In [30]:
df["latitude"] = df["latitude"].fillna(0)

In [31]:
df["latitude"] = df["latitude"].fillna(df["latitude"].mean())

In [32]:
df["latitude"] = df["latitude"].ffill()
df["latitude"] = df["latitude"].bfill()

In [33]:
df["location_name"] = df["location_name"].str.replace("+","")

In [34]:
df["latitude"] = df["latitude"].astype(int)

In [37]:
df["country"].str.lower()

0         afghanistan
1             albania
2             algeria
3             andorra
4              angola
             ...
135068      venezuela
135069        vietnam
135070          yemen
135071         zambia
135072       zimbabwe
Name: country, Length: 135073, dtype: object