#### 21/04/2026 (Day 2)

# GLOBAL WEATHER

This is an analysis project to understand the weather of countries in 2024

In [40]:
import pandas as pd

# Loading data

In [41]:
df=pd.read_csv("GlobalWeatherRepository - GlobalWeatherRepository.csv")

In [42]:
df.sample(5)

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
18662,Guinea,Conakry,9.5100,-13.7100,Africa/Conakry,1724242500,2024-08-21 12:15,25.1,77.2,Heavy rain,...,0.600,5.600,1,1,06:46,19:09,20:49,08:19,Waning Gibbous,98
33891,Saint Vincent and the Grenadines,Kingstown,13.1333,-61.2167,America/St_Vincent,1730970000,2024-11-07 05:00,28.4,83.2,Patchy rain nearby,...,12.062,21.964,1,2,06:01,17:36,11:17,22:51,Waxing Crescent,27
114547,San Marino,San Marino,43.9333,12.4500,Europe/San_Marino,1766733300,2025-12-26 08:15,10.2,50.4,Partly cloudy,...,5.626,9.226,1,1,07:44,16:38,11:21,23:21,Waxing Crescent,31
105768,Saint Kitts and Nevis,Basseterre,17.3000,-62.7167,America/St_Kitts,1762847100,2025-11-11 03:45,27.3,81.1,Patchy rain nearby,...,7.650,11.350,1,1,06:14,17:36,23:53,12:16,Last Quarter,61
35087,Thailand,Bangkok,13.7500,100.5167,Asia/Bangkok,1731488400,2024-11-13 16:00,34.3,93.7,Partly cloudy,...,64.195,93.055,3,8,06:17,17:48,15:38,03:22,Waxing Gibbous,86

In [43]:
df.shape

(135073, 41)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135073 entries, 0 to 135072
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       135073 non-null  object
 1   location_name                 135073 non-null  object
 2   latitude                      135073 non-null  float64
 3   longitude                     135073 non-null  float64
 4   timezone                      135073 non-null  object
 5   last_updated_epoch            135073 non-null  int64
 6   last_updated                  135073 non-null  object
 7   temperature_celsius           135073 non-null  float64
 8   temperature_fahrenheit        135073 non-null  float64
 9   condition_text                135073 non-null  object
 10  wind_mph                      135073 non-null  float64
 11  wind_kph                      135073 non-null  float64
 12  wind_degree                   135073 non-null  int64
 13  wind_direction                135073 non-null  object
 14  pressure_mb                   135073 non-null  int64
 15  pressure_in                   135073 non-null  float64
 16  precip_mm                     135073 non-null  float64
 17  precip_in                     135073 non-null  float64
 18  humidity                      135073 non-null  int64
 19  cloud                         135073 non-null  int64
 20  feels_like_celsius            135073 non-null  float64
 21  feels_like_fahrenheit         135073 non-null  float64
 22  visibility_km                 135073 non-null  float64
 23  visibility_miles              135073 non-null  int64
 24  uv_index                      135073 non-null  float64
 25  gust_mph                      135073 non-null  float64
 26  gust_kph                      135073 non-null  float64
 27  air_quality_Carbon_Monoxide   135073 non-null  float64
 28  air_quality_Ozone             135073 non-null  float64
 29  air_quality_Nitrogen_dioxide  135073 non-null  float64
 30  air_quality_Sulphur_dioxide   135073 non-null  float64
 31  air_quality_PM2.5             135073 non-null  float64
 32  air_quality_PM10              135073 non-null  float64
 33  air_quality_us-epa-index      135073 non-null  int64
 34  air_quality_gb-defra-index    135073 non-null  int64
 35  sunrise                       135073 non-null  object
 36  sunset                        135073 non-null  object
 37  moonrise                      135073 non-null  object
 38  moonset                       135073 non-null  object
 39  moon_phase                    135073 non-null  object
 40  moon_illumination             135073 non-null  int64
dtypes: float64(21), int64(9), object(11)
memory usage: 42.3+ MB

In [45]:
df.describe()

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,135073.000000,135073.000000,1.350730e+05,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,...,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000
mean,19.208948,21.961711,1.745908e+09,21.283607,70.312259,8.021764,12.913410,168.894909,1014.069244,29.944845,...,18.264350,461.415911,58.100332,15.007413,10.365922,24.211112,48.433111,1.699200,2.605791,49.986444
std,24.416748,65.787645,1.734686e+07,9.699084,17.458216,7.225402,11.624983,103.706143,10.369057,0.306156,...,13.829708,758.835655,30.777578,23.723174,35.691840,36.911798,149.473695,0.941003,2.445307,35.022525
min,-41.300000,-175.200000,1.715849e+09,-29.800000,-21.600000,2.200000,3.600000,1.000000,947.000000,27.960000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,4.050300,-6.836100,1.730970e+09,16.000000,60.800000,3.800000,6.100000,80.000000,1010.000000,29.830000,...,10.300000,203.500000,38.000000,1.665000,1.110000,7.050000,9.990000,1.000000,1.000000,15.000000
50%,17.250000,23.236100,1.745916e+09,24.000000,75.200000,6.700000,10.800000,161.000000,1014.000000,29.930000,...,15.300000,294.150000,55.000000,5.550000,2.405000,14.200000,19.980000,1.000000,2.000000,50.000000
75%,40.400000,49.882200,1.760860e+09,28.000000,82.400000,11.000000,17.600000,256.000000,1018.000000,30.060000,...,24.200000,460.650000,74.000000,17.390000,8.325000,27.750000,41.450000,2.000000,3.000000,85.000000
max,64.150000,179.220000,1.775975e+09,49.200000,120.600000,1841.200000,2963.200000,360.000000,3006.000000,88.770000,...,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000

# Checking Data Type

In [46]:
df.dtypes

country                          object
location_name                    object
latitude                        float64
longitude                       float64
timezone                         object
last_updated_epoch                int64
last_updated                     object
temperature_celsius             float64
temperature_fahrenheit          float64
condition_text                   object
wind_mph                        float64
wind_kph                        float64
wind_degree                       int64
wind_direction                   object
pressure_mb                       int64
pressure_in                     float64
precip_mm                       float64
precip_in                       float64
humidity                          int64
cloud                             int64
feels_like_celsius              float64
feels_like_fahrenheit           float64
visibility_km                   float64
visibility_miles                  int64
uv_index                        float64
gust_mph                        float64
gust_kph                        float64
air_quality_Carbon_Monoxide     float64
air_quality_Ozone               float64
air_quality_Nitrogen_dioxide    float64
air_quality_Sulphur_dioxide     float64
air_quality_PM2.5               float64
air_quality_PM10                float64
air_quality_us-epa-index          int64
air_quality_gb-defra-index        int64
sunrise                          object
sunset                           object
moonrise                         object
moonset                          object
moon_phase                       object
moon_illumination                 int64
dtype: object

In [47]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='object')

In [48]:
df["country"]

0         Afghanistan
1             Albania
2             Algeria
3             Andorra
4              Angola
             ...
135068      Venezuela
135069        Vietnam
135070          Yemen
135071         Zambia
135072       Zimbabwe
Name: country, Length: 135073, dtype: object

In [49]:
df["sunset"]

0         18:50
1         19:54
2         19:50
3         21:11
4         17:55
          ...
135068    18:38
135069    18:14
135070    18:17
135071    18:01
135072    17:49
Name: sunset, Length: 135073, dtype: object

In [50]:
df[["longitude","latitude"]]

        longitude  latitude
0         69.1800   34.5200
1         19.8200   41.3300
2          3.0500   36.7600
3          1.5200   42.5000
4         13.2300   -8.8400
...           ...       ...
135068   -66.9167   10.5000
135069   105.8500   21.0333
135070    44.2067   15.3547
135071    28.2833  -15.4167
135072    31.0447  -17.8178

[135073 rows x 2 columns]

In [51]:
place = df[['country','location_name']]

In [52]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.40,26.60,1,1,04:50,18:50,12:12,01:11,Waxing Gibbous,55
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.10,2.00,1,1,05:21,19:54,12:58,02:14,Waxing Gibbous,55
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.40,18.40,1,1,05:40,19:50,13:15,02:14,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.70,0.90,1,1,06:31,21:11,14:12,03:31,Waxing Gibbous,55
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.40,262.30,5,10,06:12,17:55,13:17,00:38,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30,19.1,66.3,Partly Cloudy,...,16.35,18.15,2,2,06:18,18:38,02:36,14:31,Waning Crescent,31
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30,34.2,93.6,Sunny,...,61.15,64.45,3,8,05:41,18:14,02:02,13:21,Waning Crescent,35
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30,19.3,66.7,Sunny,...,7.45,15.35,1,1,05:51,18:17,02:06,13:45,Waning Crescent,34
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30,18.5,65.3,Sunny,...,5.45,6.15,1,1,06:14,18:01,01:26,14:30,Waning Crescent,33
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30,17.4,63.3,Sunny,...,19.85,20.55,2,2,06:04,17:49,01:10,14:22,Waning Crescent,33

#### 22/04/2026 (Day 3)

# Filtering The Data

In [53]:
df[df['temperature_celsius']==25]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
31,Cameroon,Yaounde,3.8700,11.5200,Africa/Douala,1715849100,2024-05-16 09:45,25.0,76.9,Partly Cloudy,...,25.600,31.200,2,3,06:01,18:19,13:13,00:59,Waxing Gibbous,55
43,Cyprus,Nicosia,35.1700,33.3700,Asia/Famagusta,1715849100,2024-05-16 11:45,25.0,77.0,Partly cloudy,...,7.700,13.500,1,1,05:42,19:45,13:11,02:08,Waxing Gibbous,55
82,Israel,Jerusalem,31.7800,35.2300,Asia/Jerusalem,1715849100,2024-05-16 11:45,25.0,77.0,Partly cloudy,...,5.000,9.400,1,1,05:42,19:30,13:07,01:55,Waxing Gibbous,55
144,Rwanda,Kigali,-1.9500,30.0600,Africa/Kigali,1715849100,2024-05-16 10:45,25.0,77.0,Partly cloudy,...,4.200,6.300,1,1,05:55,17:57,13:02,00:36,Waxing Gibbous,55
172,Tanzania,Dodoma,-6.1800,35.7500,Africa/Dar_es_Salaam,1715849100,2024-05-16 11:45,25.0,77.0,Partly cloudy,...,1.900,3.400,1,1,06:38,18:28,13:43,01:08,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134298,Antigua and Barbuda,Saint John's,17.1167,-61.8500,America/Antigua,1775716200,2026-04-09 02:30,25.0,77.0,Light rain,...,11.909,17.909,1,1,05:56,18:22,00:12,11:20,Last Quarter,60
134438,Saint Kitts and Nevis,Basseterre,17.3000,-62.7167,America/St_Kitts,1775717100,2026-04-09 02:45,25.0,77.0,Patchy rain nearby,...,9.750,14.150,1,1,05:59,18:25,00:16,11:24,Last Quarter,60
134460,Suriname,Paramaribo,5.8333,-55.1667,America/Paramaribo,1775717100,2026-04-09 03:45,25.0,77.0,Partly cloudy,...,12.350,19.050,1,2,06:36,18:49,00:18,12:17,Last Quarter,60
134633,Saint Kitts and Nevis,Basseterre,17.3000,-62.7167,America/St_Kitts,1775803500,2026-04-10 02:45,25.0,77.0,Patchy rain nearby,...,5.850,8.550,1,1,05:59,18:26,01:03,12:17,Last Quarter,50
134687,Angola,Luanda,-8.8383,13.2344,Africa/Luanda,1775889000,2026-04-11 07:30,25.0,77.0,Partly cloudy,...,8.250,8.950,1,1,06:10,18:06,00:47,13:40,Waning Crescent,43

In [54]:
df[df['moon_phase']=='New Moon']

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
4285,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1717682400,2024-06-06 18:30,18.0,64.3,Patchy rain nearby,...,3.90,8.20,1,1,04:40,19:04,04:02,19:18,New Moon,0
4286,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1717682400,2024-06-06 16:00,32.0,89.6,Sunny,...,4.50,5.10,1,1,05:08,20:11,04:31,20:41,New Moon,0
4287,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1717682400,2024-06-06 15:00,32.0,89.6,Sunny,...,16.40,34.80,2,2,05:29,20:04,04:58,20:33,New Moon,0
4288,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1717682400,2024-06-06 16:00,22.5,72.6,Patchy rain nearby,...,2.20,3.40,1,1,06:17,21:29,05:43,22:03,New Moon,0
4289,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1717682400,2024-06-06 15:00,26.0,78.8,Partly cloudy,...,7.30,25.20,1,1,06:17,17:55,06:04,17:55,New Moon,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130387,Vanuatu,Port Vila,-17.7333,168.3167,Pacific/Efate,1773901800,2026-03-19 17:30,28.3,82.9,Partly cloudy,...,9.75,12.25,1,1,05:50,17:59,05:39,17:59,New Moon,0
130389,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1773901800,2026-03-19 13:30,27.4,81.3,Partly cloudy,...,47.55,51.05,3,5,06:02,18:07,05:57,18:26,New Moon,0
130390,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1773901800,2026-03-19 09:30,20.1,68.2,Patchy rain nearby,...,10.85,54.55,1,1,06:08,18:14,06:10,18:40,New Moon,0
130391,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1773901800,2026-03-19 08:30,19.1,66.3,Mist,...,8.55,8.65,1,1,06:10,18:18,06:20,18:34,New Moon,0
130392,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1773901800,2026-03-19 08:30,17.8,64.1,Patchy rain nearby,...,3.15,3.15,1,1,05:59,18:07,06:09,18:22,New Moon,0

In [55]:
df[df['condition_text']=='patchy late rain with thunder']

Empty DataFrame
Columns: [country, location_name, latitude, longitude, timezone, last_updated_epoch, last_updated, temperature_celsius, temperature_fahrenheit, condition_text, wind_mph, wind_kph, wind_degree, wind_direction, pressure_mb, pressure_in, precip_mm, precip_in, humidity, cloud, feels_like_celsius, feels_like_fahrenheit, visibility_km, visibility_miles, uv_index, gust_mph, gust_kph, air_quality_Carbon_Monoxide, air_quality_Ozone, air_quality_Nitrogen_dioxide, air_quality_Sulphur_dioxide, air_quality_PM2.5, air_quality_PM10, air_quality_us-epa-index, air_quality_gb-defra-index, sunrise, sunset, moonrise, moonset, moon_phase, moon_illumination]
Index: []

[0 rows x 41 columns]

In [56]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.40,26.60,1,1,04:50,18:50,12:12,01:11,Waxing Gibbous,55
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.10,2.00,1,1,05:21,19:54,12:58,02:14,Waxing Gibbous,55
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.40,18.40,1,1,05:40,19:50,13:15,02:14,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.70,0.90,1,1,06:31,21:11,14:12,03:31,Waxing Gibbous,55
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.40,262.30,5,10,06:12,17:55,13:17,00:38,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30,19.1,66.3,Partly Cloudy,...,16.35,18.15,2,2,06:18,18:38,02:36,14:31,Waning Crescent,31
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30,34.2,93.6,Sunny,...,61.15,64.45,3,8,05:41,18:14,02:02,13:21,Waning Crescent,35
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30,19.3,66.7,Sunny,...,7.45,15.35,1,1,05:51,18:17,02:06,13:45,Waning Crescent,34
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30,18.5,65.3,Sunny,...,5.45,6.15,1,1,06:14,18:01,01:26,14:30,Waning Crescent,33
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30,17.4,63.3,Sunny,...,19.85,20.55,2,2,06:04,17:49,01:10,14:22,Waning Crescent,33

In [57]:
df[df['moon_illumination']==0]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
4285,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1717682400,2024-06-06 18:30,18.0,64.3,Patchy rain nearby,...,3.90,8.20,1,1,04:40,19:04,04:02,19:18,New Moon,0
4286,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1717682400,2024-06-06 16:00,32.0,89.6,Sunny,...,4.50,5.10,1,1,05:08,20:11,04:31,20:41,New Moon,0
4287,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1717682400,2024-06-06 15:00,32.0,89.6,Sunny,...,16.40,34.80,2,2,05:29,20:04,04:58,20:33,New Moon,0
4288,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1717682400,2024-06-06 16:00,22.5,72.6,Patchy rain nearby,...,2.20,3.40,1,1,06:17,21:29,05:43,22:03,New Moon,0
4289,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1717682400,2024-06-06 15:00,26.0,78.8,Partly cloudy,...,7.30,25.20,1,1,06:17,17:55,06:04,17:55,New Moon,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130555,South Korea,Seoul,37.5664,126.9997,Asia/Seoul,1773989100,2026-03-20 15:45,13.3,55.9,Sunny,...,26.95,35.85,2,3,06:36,18:43,06:56,20:14,Waxing Crescent,0
130567,Timor-Leste,Dili,-8.5586,125.5736,Asia/Dili,1773989100,2026-03-20 15:45,26.4,79.5,Patchy rain nearby,...,2.65,2.85,1,1,06:42,18:49,07:28,19:41,Waxing Crescent,0
130569,Tonga,Nuku`Aloia,-21.1333,-175.2000,Pacific/Tongatapu,1773989100,2026-03-20 19:45,28.0,82.4,Light rain shower,...,3.15,4.55,1,1,06:44,18:52,07:28,19:28,Waxing Crescent,0
130574,Tuvalu,Funafuti,-8.5167,179.2167,Pacific/Funafuti,1773989100,2026-03-20 18:45,28.1,82.6,Partly cloudy,...,2.05,2.65,1,1,06:07,18:14,06:45,18:59,Waxing Crescent,0
130582,Vanuatu,Port Vila,-17.7333,168.3167,Pacific/Efate,1773989100,2026-03-20 17:45,29.0,84.2,Partly cloudy,...,2.35,3.05,1,1,05:51,17:58,06:35,18:37,Waxing Crescent,0

In [58]:
df[(df['temperature_celsius']==20) & (df['condition_text']=='sunny')]

Empty DataFrame
Columns: [country, location_name, latitude, longitude, timezone, last_updated_epoch, last_updated, temperature_celsius, temperature_fahrenheit, condition_text, wind_mph, wind_kph, wind_degree, wind_direction, pressure_mb, pressure_in, precip_mm, precip_in, humidity, cloud, feels_like_celsius, feels_like_fahrenheit, visibility_km, visibility_miles, uv_index, gust_mph, gust_kph, air_quality_Carbon_Monoxide, air_quality_Ozone, air_quality_Nitrogen_dioxide, air_quality_Sulphur_dioxide, air_quality_PM2.5, air_quality_PM10, air_quality_us-epa-index, air_quality_gb-defra-index, sunrise, sunset, moonrise, moonset, moon_phase, moon_illumination]
Index: []

[0 rows x 41 columns]

In [59]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.40,26.60,1,1,04:50,18:50,12:12,01:11,Waxing Gibbous,55
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.10,2.00,1,1,05:21,19:54,12:58,02:14,Waxing Gibbous,55
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.40,18.40,1,1,05:40,19:50,13:15,02:14,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.70,0.90,1,1,06:31,21:11,14:12,03:31,Waxing Gibbous,55
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.40,262.30,5,10,06:12,17:55,13:17,00:38,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30,19.1,66.3,Partly Cloudy,...,16.35,18.15,2,2,06:18,18:38,02:36,14:31,Waning Crescent,31
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30,34.2,93.6,Sunny,...,61.15,64.45,3,8,05:41,18:14,02:02,13:21,Waning Crescent,35
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30,19.3,66.7,Sunny,...,7.45,15.35,1,1,05:51,18:17,02:06,13:45,Waning Crescent,34
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30,18.5,65.3,Sunny,...,5.45,6.15,1,1,06:14,18:01,01:26,14:30,Waning Crescent,33
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30,17.4,63.3,Sunny,...,19.85,20.55,2,2,06:04,17:49,01:10,14:22,Waning Crescent,33

# Data Cleaning

In [60]:
df['last_updated'] = pd.to_datetime(df['last_updated'])

In [61]:
df['date'] =df['last_updated'].dt.date

In [62]:
df['time'] =df['last_updated'].dt.time

In [63]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,date,time
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,1,1,04:50,18:50,12:12,01:11,Waxing Gibbous,55,2024-05-16,13:15:00
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,1,1,05:21,19:54,12:58,02:14,Waxing Gibbous,55,2024-05-16,10:45:00
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,1,1,05:40,19:50,13:15,02:14,Waxing Gibbous,55,2024-05-16,09:45:00
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,1,1,06:31,21:11,14:12,03:31,Waxing Gibbous,55,2024-05-16,10:45:00
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,5,10,06:12,17:55,13:17,00:38,Waxing Gibbous,55,2024-05-16,09:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,2,2,06:18,18:38,02:36,14:31,Waning Crescent,31,2026-04-12,02:30:00
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,3,8,05:41,18:14,02:02,13:21,Waning Crescent,35,2026-04-12,13:30:00
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,1,1,05:51,18:17,02:06,13:45,Waning Crescent,34,2026-04-12,09:30:00
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,1,1,06:14,18:01,01:26,14:30,Waning Crescent,33,2026-04-12,08:30:00
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,2,2,06:04,17:49,01:10,14:22,Waning Crescent,33,2026-04-12,08:30:00

In [64]:
print(df.isnull().sum())

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
date                            0
time                            0
dtype: int64

# Remove Invalid Rows

In [65]:
set(df["country"].to_list())

{'Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'B��lgica',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Democratic Republic of Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Estonie',
 'Ethiopia',
 'Fiji Islands',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'Inde',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jemen',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Komoren',
 'Kosovo',
 'Kuwait',
 'Kyrghyzstan',
 "Lao People's Democratic Republic",
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Letonia',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Mal��sia',
 'Marrocos',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Mexique',
 'Micronesia',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Pol��nia',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Saint-Vincent-et-les-Grenadines',
 'Samoa',
 'San Marino',
 'Saudi Arabia',
 'Saudi Arabien',
 'Senegal',
 'Serbia',
 'Seychelles Islands',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Korea',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'S��dkorea',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turkm��nistan',
 'Tuvalu',
 'USA United States of America',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States of America',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican City',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe',
 '������',
 '������������',
 '����������������',
 '������������������'}

In [66]:
invalid_rows = df[df['country'].str.contains('�',na=False)]

In [67]:
invalid_rows

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,date,time
11474,Mal��sia,Ivory Ivory Ban,4.63,118.37,Asia/Kuching,1720875600,2024-07-13 21:00:00,24.3,75.7,Light rain shower,...,1,1,06:01,18:23,11:28,23:43,First Quarter,41,2024-07-13,21:00:00
11484,����������������,Costa Rica,6.43,-70.92,America/Bogota,1720875600,2024-07-13 08:00:00,23.1,73.5,Mist,...,1,1,05:23,18:02,11:25,23:30,First Quarter,41,2024-07-13,08:00:00
11504,������������������,New Guatemala,14.62,-90.53,America/Guatemala,1720875600,2024-07-13 07:00:00,15.9,60.6,Mist,...,3,4,05:41,18:35,11:54,23:52,First Quarter,41,2024-07-13,07:00:00
11526,������������,Beirut,51.12,17.53,Europe/Warsaw,1720875600,2024-07-13 15:00:00,24.2,75.5,Cloudy,...,1,1,04:50,21:00,12:56,23:51,First Quarter,41,2024-07-13,15:00:00
11540,Pol��nia,Moldova,53.33,21.62,Europe/Warsaw,1720875600,2024-07-13 15:00:00,27.7,81.9,Partly Cloudy,...,1,1,04:22,20:56,12:42,23:31,First Quarter,41,2024-07-13,15:00:00
11547,������������,Yaren,39.55,27.62,Europe/Istanbul,1720875600,2024-07-13 16:00:00,34.0,93.2,Partly cloudy,...,1,1,05:54,20:37,13:02,00:06,First Quarter,41,2024-07-13,16:00:00
11577,S��dkorea,Seoul,37.57,127.00,Asia/Seoul,1720875600,2024-07-13 22:00:00,26.1,79.0,Clear,...,4,9,05:22,19:54,12:07,23:45,First Quarter,41,2024-07-13,22:00:00
11581,B��lgica,Bern,51.10,4.75,Europe/Brussels,1720875600,2024-07-13 15:00:00,17.4,63.3,Partly cloudy,...,1,1,05:49,21:23,13:34,00:24,First Quarter,41,2024-07-13,15:00:00
11588,Turkm��nistan,Krasnyy Turkmenistan,37.70,65.37,Asia/Ashgabat,1720875600,2024-07-13 18:00:00,37.8,100.1,Sunny,...,1,1,05:28,20:01,12:23,23:55,First Quarter,41,2024-07-13,18:00:00
11592,������,-Kingdom,38.85,34.65,Europe/Istanbul,1720875600,2024-07-13 16:00:00,29.7,85.4,Sunny,...,1,1,05:28,20:07,12:32,23:59,First Quarter,41,2024-07-13,16:00:00

In [68]:
df= df[~df['country'].str.contains('�',na=False)]

In [69]:
set(df["country"].to_list())

{'Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Democratic Republic of Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Estonie',
 'Ethiopia',
 'Fiji Islands',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'Inde',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jemen',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Komoren',
 'Kosovo',
 'Kuwait',
 'Kyrghyzstan',
 "Lao People's Democratic Republic",
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Letonia',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marrocos',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Mexique',
 'Micronesia',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Saint-Vincent-et-les-Grenadines',
 'Samoa',
 'San Marino',
 'Saudi Arabia',
 'Saudi Arabien',
 'Senegal',
 'Serbia',
 'Seychelles Islands',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Korea',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Tuvalu',
 'USA United States of America',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States of America',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican City',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe'}

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 135063 entries, 0 to 135072
Data columns (total 43 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       135063 non-null  object
 1   location_name                 135063 non-null  object
 2   latitude                      135063 non-null  float64
 3   longitude                     135063 non-null  float64
 4   timezone                      135063 non-null  object
 5   last_updated_epoch            135063 non-null  int64
 6   last_updated                  135063 non-null  datetime64[ns]
 7   temperature_celsius           135063 non-null  float64
 8   temperature_fahrenheit        135063 non-null  float64
 9   condition_text                135063 non-null  object
 10  wind_mph                      135063 non-null  float64
 11  wind_kph                      135063 non-null  float64
 12  wind_degree                   135063 non-null  int64
 13  wind_direction                135063 non-null  object
 14  pressure_mb                   135063 non-null  int64
 15  pressure_in                   135063 non-null  float64
 16  precip_mm                     135063 non-null  float64
 17  precip_in                     135063 non-null  float64
 18  humidity                      135063 non-null  int64
 19  cloud                         135063 non-null  int64
 20  feels_like_celsius            135063 non-null  float64
 21  feels_like_fahrenheit         135063 non-null  float64
 22  visibility_km                 135063 non-null  float64
 23  visibility_miles              135063 non-null  int64
 24  uv_index                      135063 non-null  float64
 25  gust_mph                      135063 non-null  float64
 26  gust_kph                      135063 non-null  float64
 27  air_quality_Carbon_Monoxide   135063 non-null  float64
 28  air_quality_Ozone             135063 non-null  float64
 29  air_quality_Nitrogen_dioxide  135063 non-null  float64
 30  air_quality_Sulphur_dioxide   135063 non-null  float64
 31  air_quality_PM2.5             135063 non-null  float64
 32  air_quality_PM10              135063 non-null  float64
 33  air_quality_us-epa-index      135063 non-null  int64
 34  air_quality_gb-defra-index    135063 non-null  int64
 35  sunrise                       135063 non-null  object
 36  sunset                        135063 non-null  object
 37  moonrise                      135063 non-null  object
 38  moonset                       135063 non-null  object
 39  moon_phase                    135063 non-null  object
 40  moon_illumination             135063 non-null  int64
 41  date                          135063 non-null  object
 42  time                          135063 non-null  object
dtypes: datetime64[ns](1), float64(21), int64(9), object(12)
memory usage: 45.3+ MB

# Find Duplicates

In [71]:
df.duplicated().sum()

np.int64(0)

# Remove Columns

In [72]:
redundant_cols = [
    'temperature_fahrenheit',
    'wind_mph',
    'pressure_in',
    'precip_in',
    'visibility_miles',
    'feels_like_fahrenheit',
    'gust_mph',
    'sunrise',
]

In [73]:
df.drop(columns=['temperature_fahrenheit',
    'wind_mph',
    'pressure_in',
    'precip_in',
    'visibility_miles',
    'feels_like_fahrenheit',
    'gust_mph',
    'sunrise','sunset','moonset','moonrise','moon_phase','moon_illumination'])

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,condition_text,wind_kph,...,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,date,time
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,...,277.00,103.0,1.10,0.20,8.40,26.60,1,1,2024-05-16,13:15:00
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,Partly cloudy,11.2,...,193.60,97.3,0.90,0.10,1.10,2.00,1,1,2024-05-16,10:45:00
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,Sunny,15.1,...,540.70,12.2,65.10,13.40,10.40,18.40,1,1,2024-05-16,09:45:00
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,Light drizzle,11.9,...,170.20,64.4,1.60,0.20,0.70,0.90,1,1,2024-05-16,10:45:00
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,Partly cloudy,13.0,...,2964.00,19.0,72.70,31.50,183.40,262.30,5,10,2024-05-16,09:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,Partly Cloudy,3.6,...,379.85,46.0,7.95,2.35,16.35,18.15,2,2,2026-04-12,02:30:00
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,Sunny,11.2,...,1034.85,62.0,30.75,17.85,61.15,64.45,3,8,2026-04-12,13:30:00
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,Sunny,6.5,...,147.85,47.0,3.35,1.35,7.45,15.35,1,1,2026-04-12,09:30:00
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,Sunny,13.7,...,118.85,54.0,2.35,1.85,5.45,6.15,1,1,2026-04-12,08:30:00
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,Sunny,7.9,...,200.85,35.0,7.75,2.05,19.85,20.55,2,2,2026-04-12,08:30:00

##### 23/04/2026 (Day 4)

# Drop Columns

In [74]:
print(df.columns)

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination',
       'date', 'time'],
      dtype='object')

In [75]:
print(df.shape)

(135063, 43)

In [76]:
df = df.drop(columns=redundant_cols, errors='ignore')

In [77]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,condition_text,wind_kph,...,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunset,moonrise,moonset,moon_phase,moon_illumination,date,time
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,...,26.60,1,1,18:50,12:12,01:11,Waxing Gibbous,55,2024-05-16,13:15:00
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,Partly cloudy,11.2,...,2.00,1,1,19:54,12:58,02:14,Waxing Gibbous,55,2024-05-16,10:45:00
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,Sunny,15.1,...,18.40,1,1,19:50,13:15,02:14,Waxing Gibbous,55,2024-05-16,09:45:00
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,Light drizzle,11.9,...,0.90,1,1,21:11,14:12,03:31,Waxing Gibbous,55,2024-05-16,10:45:00
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,Partly cloudy,13.0,...,262.30,5,10,17:55,13:17,00:38,Waxing Gibbous,55,2024-05-16,09:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,Partly Cloudy,3.6,...,18.15,2,2,18:38,02:36,14:31,Waning Crescent,31,2026-04-12,02:30:00
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,Sunny,11.2,...,64.45,3,8,18:14,02:02,13:21,Waning Crescent,35,2026-04-12,13:30:00
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,Sunny,6.5,...,15.35,1,1,18:17,02:06,13:45,Waning Crescent,34,2026-04-12,09:30:00
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,Sunny,13.7,...,6.15,1,1,18:01,01:26,14:30,Waning Crescent,33,2026-04-12,08:30:00
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,Sunny,7.9,...,20.55,2,2,17:49,01:10,14:22,Waning Crescent,33,2026-04-12,08:30:00

In [78]:
print(df.columns)

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'condition_text', 'wind_kph', 'wind_degree', 'wind_direction',
       'pressure_mb', 'precip_mm', 'humidity', 'cloud', 'feels_like_celsius',
       'visibility_km', 'uv_index', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunset',
       'moonrise', 'moonset', 'moon_phase', 'moon_illumination', 'date',
       'time'],
      dtype='object')

In [79]:
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,condition_text,wind_kph,...,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunset,moonrise,moonset,moon_phase,moon_illumination,date,time
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,...,26.6,1,1,18:50,12:12,01:11,Waxing Gibbous,55,2024-05-16,13:15:00
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,Partly cloudy,11.2,...,2.0,1,1,19:54,12:58,02:14,Waxing Gibbous,55,2024-05-16,10:45:00
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,Sunny,15.1,...,18.4,1,1,19:50,13:15,02:14,Waxing Gibbous,55,2024-05-16,09:45:00
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,Light drizzle,11.9,...,0.9,1,1,21:11,14:12,03:31,Waxing Gibbous,55,2024-05-16,10:45:00
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,Partly cloudy,13.0,...,262.3,5,10,17:55,13:17,00:38,Waxing Gibbous,55,2024-05-16,09:45:00

In [80]:
df['last_updated'] = pd.to_datetime(df['last_updated'])

In [81]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,condition_text,wind_kph,...,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunset,moonrise,moonset,moon_phase,moon_illumination,date,time
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,...,26.60,1,1,18:50,12:12,01:11,Waxing Gibbous,55,2024-05-16,13:15:00
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,Partly cloudy,11.2,...,2.00,1,1,19:54,12:58,02:14,Waxing Gibbous,55,2024-05-16,10:45:00
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,Sunny,15.1,...,18.40,1,1,19:50,13:15,02:14,Waxing Gibbous,55,2024-05-16,09:45:00
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,Light drizzle,11.9,...,0.90,1,1,21:11,14:12,03:31,Waxing Gibbous,55,2024-05-16,10:45:00
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,Partly cloudy,13.0,...,262.30,5,10,17:55,13:17,00:38,Waxing Gibbous,55,2024-05-16,09:45:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,Partly Cloudy,3.6,...,18.15,2,2,18:38,02:36,14:31,Waning Crescent,31,2026-04-12,02:30:00
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,Sunny,11.2,...,64.45,3,8,18:14,02:02,13:21,Waning Crescent,35,2026-04-12,13:30:00
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,Sunny,6.5,...,15.35,1,1,18:17,02:06,13:45,Waning Crescent,34,2026-04-12,09:30:00
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,Sunny,13.7,...,6.15,1,1,18:01,01:26,14:30,Waning Crescent,33,2026-04-12,08:30:00
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,Sunny,7.9,...,20.55,2,2,17:49,01:10,14:22,Waning Crescent,33,2026-04-12,08:30:00

# 2. Check missing values

In [82]:
print(df.isnull().sum())

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
condition_text                  0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
precip_mm                       0
humidity                        0
cloud                           0
feels_like_celsius              0
visibility_km                   0
uv_index                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
date                            0
time                            0
dtype: int64

# 3. Split Columns

In [83]:
split_columns = df['timezone'].str.split('/',expand=True)

In [84]:
split_columns.head()

        0        1     2
0    Asia    Kabul  None
1  Europe   Tirane  None
2  Africa  Algiers  None
3  Europe  Andorra  None
4  Africa   Luanda  None

In [85]:
df['timezone'] = df['timezone'].fillna('unknown/unknown')

In [86]:
split_columns = df['timezone'].str.split('/',n=1,expand=True)

In [87]:
df['continent'] = split_columns[0]

In [88]:
df['city'] = split_columns[1]

In [89]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,condition_text,wind_kph,...,air_quality_gb-defra-index,sunset,moonrise,moonset,moon_phase,moon_illumination,date,time,continent,city
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,...,1,18:50,12:12,01:11,Waxing Gibbous,55,2024-05-16,13:15:00,Asia,Kabul
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,Partly cloudy,11.2,...,1,19:54,12:58,02:14,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Tirane
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,Sunny,15.1,...,1,19:50,13:15,02:14,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Algiers
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,Light drizzle,11.9,...,1,21:11,14:12,03:31,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Andorra
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,Partly cloudy,13.0,...,10,17:55,13:17,00:38,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Luanda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,Partly Cloudy,3.6,...,2,18:38,02:36,14:31,Waning Crescent,31,2026-04-12,02:30:00,America,Caracas
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,Sunny,11.2,...,8,18:14,02:02,13:21,Waning Crescent,35,2026-04-12,13:30:00,Asia,Bangkok
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,Sunny,6.5,...,1,18:17,02:06,13:45,Waning Crescent,34,2026-04-12,09:30:00,Asia,Aden
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,Sunny,13.7,...,1,18:01,01:26,14:30,Waning Crescent,33,2026-04-12,08:30:00,Africa,Lusaka
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,Sunny,7.9,...,2,17:49,01:10,14:22,Waning Crescent,33,2026-04-12,08:30:00,Africa,Harare

In [90]:
df[['timezone','continent','city']].head()

         timezone continent     city
0      Asia/Kabul      Asia    Kabul
1   Europe/Tirane    Europe   Tirane
2  Africa/Algiers    Africa  Algiers
3  Europe/Andorra    Europe  Andorra
4   Africa/Luanda    Africa   Luanda

In [91]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,condition_text,wind_kph,...,air_quality_gb-defra-index,sunset,moonrise,moonset,moon_phase,moon_illumination,date,time,continent,city
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,...,1,18:50,12:12,01:11,Waxing Gibbous,55,2024-05-16,13:15:00,Asia,Kabul
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,Partly cloudy,11.2,...,1,19:54,12:58,02:14,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Tirane
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,Sunny,15.1,...,1,19:50,13:15,02:14,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Algiers
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,Light drizzle,11.9,...,1,21:11,14:12,03:31,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Andorra
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,Partly cloudy,13.0,...,10,17:55,13:17,00:38,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Luanda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,Partly Cloudy,3.6,...,2,18:38,02:36,14:31,Waning Crescent,31,2026-04-12,02:30:00,America,Caracas
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,Sunny,11.2,...,8,18:14,02:02,13:21,Waning Crescent,35,2026-04-12,13:30:00,Asia,Bangkok
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,Sunny,6.5,...,1,18:17,02:06,13:45,Waning Crescent,34,2026-04-12,09:30:00,Asia,Aden
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,Sunny,13.7,...,1,18:01,01:26,14:30,Waning Crescent,33,2026-04-12,08:30:00,Africa,Lusaka
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,Sunny,7.9,...,2,17:49,01:10,14:22,Waning Crescent,33,2026-04-12,08:30:00,Africa,Harare

# 4. Standardize text columns

In [92]:
text_cols = ['country', 'location_name', 'timezone', 'condition_text', 
             'wind_direction', 'moon_phase']

for col in text_cols:
    df[col] = df[col].str.strip().str.title()

In [93]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,condition_text,wind_kph,...,air_quality_gb-defra-index,sunset,moonrise,moonset,moon_phase,moon_illumination,date,time,continent,city
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,...,1,18:50,12:12,01:11,Waxing Gibbous,55,2024-05-16,13:15:00,Asia,Kabul
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,Partly Cloudy,11.2,...,1,19:54,12:58,02:14,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Tirane
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,Sunny,15.1,...,1,19:50,13:15,02:14,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Algiers
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,Light Drizzle,11.9,...,1,21:11,14:12,03:31,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Andorra
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,Partly Cloudy,13.0,...,10,17:55,13:17,00:38,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Luanda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,Partly Cloudy,3.6,...,2,18:38,02:36,14:31,Waning Crescent,31,2026-04-12,02:30:00,America,Caracas
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,Sunny,11.2,...,8,18:14,02:02,13:21,Waning Crescent,35,2026-04-12,13:30:00,Asia,Bangkok
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,Sunny,6.5,...,1,18:17,02:06,13:45,Waning Crescent,34,2026-04-12,09:30:00,Asia,Aden
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,Sunny,13.7,...,1,18:01,01:26,14:30,Waning Crescent,33,2026-04-12,08:30:00,Africa,Lusaka
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,Sunny,7.9,...,2,17:49,01:10,14:22,Waning Crescent,33,2026-04-12,08:30:00,Africa,Harare

# 5. Remove impossible values

## Temperature check

In [94]:
df = df[(df['temperature_celsius'] > -60) & (df['temperature_celsius'] < 60)]

In [95]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,condition_text,wind_kph,...,air_quality_gb-defra-index,sunset,moonrise,moonset,moon_phase,moon_illumination,date,time,continent,city
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,...,1,18:50,12:12,01:11,Waxing Gibbous,55,2024-05-16,13:15:00,Asia,Kabul
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,Partly Cloudy,11.2,...,1,19:54,12:58,02:14,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Tirane
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,Sunny,15.1,...,1,19:50,13:15,02:14,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Algiers
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,Light Drizzle,11.9,...,1,21:11,14:12,03:31,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Andorra
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,Partly Cloudy,13.0,...,10,17:55,13:17,00:38,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Luanda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,Partly Cloudy,3.6,...,2,18:38,02:36,14:31,Waning Crescent,31,2026-04-12,02:30:00,America,Caracas
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,Sunny,11.2,...,8,18:14,02:02,13:21,Waning Crescent,35,2026-04-12,13:30:00,Asia,Bangkok
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,Sunny,6.5,...,1,18:17,02:06,13:45,Waning Crescent,34,2026-04-12,09:30:00,Asia,Aden
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,Sunny,13.7,...,1,18:01,01:26,14:30,Waning Crescent,33,2026-04-12,08:30:00,Africa,Lusaka
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,Sunny,7.9,...,2,17:49,01:10,14:22,Waning Crescent,33,2026-04-12,08:30:00,Africa,Harare

### Humidity should be 0 to 100

In [96]:
df = df[(df['humidity'] >= 0) & (df['humidity'] <= 100)]

In [97]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,condition_text,wind_kph,...,air_quality_gb-defra-index,sunset,moonrise,moonset,moon_phase,moon_illumination,date,time,continent,city
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,...,1,18:50,12:12,01:11,Waxing Gibbous,55,2024-05-16,13:15:00,Asia,Kabul
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,Partly Cloudy,11.2,...,1,19:54,12:58,02:14,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Tirane
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,Sunny,15.1,...,1,19:50,13:15,02:14,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Algiers
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,Light Drizzle,11.9,...,1,21:11,14:12,03:31,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Andorra
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,Partly Cloudy,13.0,...,10,17:55,13:17,00:38,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Luanda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,Partly Cloudy,3.6,...,2,18:38,02:36,14:31,Waning Crescent,31,2026-04-12,02:30:00,America,Caracas
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,Sunny,11.2,...,8,18:14,02:02,13:21,Waning Crescent,35,2026-04-12,13:30:00,Asia,Bangkok
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,Sunny,6.5,...,1,18:17,02:06,13:45,Waning Crescent,34,2026-04-12,09:30:00,Asia,Aden
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,Sunny,13.7,...,1,18:01,01:26,14:30,Waning Crescent,33,2026-04-12,08:30:00,Africa,Lusaka
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,Sunny,7.9,...,2,17:49,01:10,14:22,Waning Crescent,33,2026-04-12,08:30:00,Africa,Harare

#### Cloud should be 0 to 100

In [98]:
df = df[(df['cloud'] >= 0) & (df['cloud'] <= 100)]

In [99]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,condition_text,wind_kph,...,air_quality_gb-defra-index,sunset,moonrise,moonset,moon_phase,moon_illumination,date,time,continent,city
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,...,1,18:50,12:12,01:11,Waxing Gibbous,55,2024-05-16,13:15:00,Asia,Kabul
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,Partly Cloudy,11.2,...,1,19:54,12:58,02:14,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Tirane
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,Sunny,15.1,...,1,19:50,13:15,02:14,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Algiers
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,Light Drizzle,11.9,...,1,21:11,14:12,03:31,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Andorra
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,Partly Cloudy,13.0,...,10,17:55,13:17,00:38,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Luanda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,Partly Cloudy,3.6,...,2,18:38,02:36,14:31,Waning Crescent,31,2026-04-12,02:30:00,America,Caracas
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,Sunny,11.2,...,8,18:14,02:02,13:21,Waning Crescent,35,2026-04-12,13:30:00,Asia,Bangkok
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,Sunny,6.5,...,1,18:17,02:06,13:45,Waning Crescent,34,2026-04-12,09:30:00,Asia,Aden
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,Sunny,13.7,...,1,18:01,01:26,14:30,Waning Crescent,33,2026-04-12,08:30:00,Africa,Lusaka
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,Sunny,7.9,...,2,17:49,01:10,14:22,Waning Crescent,33,2026-04-12,08:30:00,Africa,Harare

##### Wind degree 0 to 360

In [100]:
df = df[(df['wind_degree'] >= 0) & (df['wind_degree'] <= 360)]

In [101]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,condition_text,wind_kph,...,air_quality_gb-defra-index,sunset,moonrise,moonset,moon_phase,moon_illumination,date,time,continent,city
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,...,1,18:50,12:12,01:11,Waxing Gibbous,55,2024-05-16,13:15:00,Asia,Kabul
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,Partly Cloudy,11.2,...,1,19:54,12:58,02:14,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Tirane
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,Sunny,15.1,...,1,19:50,13:15,02:14,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Algiers
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,Light Drizzle,11.9,...,1,21:11,14:12,03:31,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Andorra
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,Partly Cloudy,13.0,...,10,17:55,13:17,00:38,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Luanda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,Partly Cloudy,3.6,...,2,18:38,02:36,14:31,Waning Crescent,31,2026-04-12,02:30:00,America,Caracas
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,Sunny,11.2,...,8,18:14,02:02,13:21,Waning Crescent,35,2026-04-12,13:30:00,Asia,Bangkok
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,Sunny,6.5,...,1,18:17,02:06,13:45,Waning Crescent,34,2026-04-12,09:30:00,Asia,Aden
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,Sunny,13.7,...,1,18:01,01:26,14:30,Waning Crescent,33,2026-04-12,08:30:00,Africa,Lusaka
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,Sunny,7.9,...,2,17:49,01:10,14:22,Waning Crescent,33,2026-04-12,08:30:00,Africa,Harare

##### UV index positive

In [102]:
df = df[df['uv_index'] >= 0]

In [103]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,condition_text,wind_kph,...,air_quality_gb-defra-index,sunset,moonrise,moonset,moon_phase,moon_illumination,date,time,continent,city
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,...,1,18:50,12:12,01:11,Waxing Gibbous,55,2024-05-16,13:15:00,Asia,Kabul
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,Partly Cloudy,11.2,...,1,19:54,12:58,02:14,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Tirane
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,Sunny,15.1,...,1,19:50,13:15,02:14,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Algiers
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,Light Drizzle,11.9,...,1,21:11,14:12,03:31,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Andorra
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,Partly Cloudy,13.0,...,10,17:55,13:17,00:38,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Luanda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,Partly Cloudy,3.6,...,2,18:38,02:36,14:31,Waning Crescent,31,2026-04-12,02:30:00,America,Caracas
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,Sunny,11.2,...,8,18:14,02:02,13:21,Waning Crescent,35,2026-04-12,13:30:00,Asia,Bangkok
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,Sunny,6.5,...,1,18:17,02:06,13:45,Waning Crescent,34,2026-04-12,09:30:00,Asia,Aden
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,Sunny,13.7,...,1,18:01,01:26,14:30,Waning Crescent,33,2026-04-12,08:30:00,Africa,Lusaka
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,Sunny,7.9,...,2,17:49,01:10,14:22,Waning Crescent,33,2026-04-12,08:30:00,Africa,Harare

##### 6. Drop unnecessary columns

In [104]:
df = df.drop(columns=['last_updated_epoch'])

In [105]:
df

,country,location_name,latitude,longitude,timezone,last_updated,temperature_celsius,condition_text,wind_kph,wind_degree,...,air_quality_gb-defra-index,sunset,moonrise,moonset,moon_phase,moon_illumination,date,time,continent,city
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,338,...,1,18:50,12:12,01:11,Waxing Gibbous,55,2024-05-16,13:15:00,Asia,Kabul
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,2024-05-16 10:45:00,19.0,Partly Cloudy,11.2,320,...,1,19:54,12:58,02:14,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Tirane
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,2024-05-16 09:45:00,23.0,Sunny,15.1,280,...,1,19:50,13:15,02:14,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Algiers
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,2024-05-16 10:45:00,6.3,Light Drizzle,11.9,215,...,1,21:11,14:12,03:31,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Andorra
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,2024-05-16 09:45:00,26.0,Partly Cloudy,13.0,150,...,10,17:55,13:17,00:38,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Luanda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,2026-04-12 02:30:00,19.1,Partly Cloudy,3.6,178,...,2,18:38,02:36,14:31,Waning Crescent,31,2026-04-12,02:30:00,America,Caracas
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,2026-04-12 13:30:00,34.2,Sunny,11.2,245,...,8,18:14,02:02,13:21,Waning Crescent,35,2026-04-12,13:30:00,Asia,Bangkok
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,2026-04-12 09:30:00,19.3,Sunny,6.5,217,...,1,18:17,02:06,13:45,Waning Crescent,34,2026-04-12,09:30:00,Asia,Aden
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,2026-04-12 08:30:00,18.5,Sunny,13.7,90,...,1,18:01,01:26,14:30,Waning Crescent,33,2026-04-12,08:30:00,Africa,Lusaka
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,2026-04-12 08:30:00,17.4,Sunny,7.9,43,...,2,17:49,01:10,14:22,Waning Crescent,33,2026-04-12,08:30:00,Africa,Harare

# year

In [117]:
df['last_updated'] = pd.to_datetime(df['last_updated'])
df['year'] = df['last_updated'].dt.year
df['month'] = df['last_updated'].dt.month
df['hour'] = df['last_updated'].dt.hour

In [107]:
df

,country,location_name,latitude,longitude,timezone,last_updated,temperature_celsius,condition_text,wind_kph,wind_degree,...,moonset,moon_phase,moon_illumination,date,time,continent,city,year,month,hour
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,338,...,01:11,Waxing Gibbous,55,2024-05-16,13:15:00,Asia,Kabul,2024,5,13
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,2024-05-16 10:45:00,19.0,Partly Cloudy,11.2,320,...,02:14,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Tirane,2024,5,10
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,2024-05-16 09:45:00,23.0,Sunny,15.1,280,...,02:14,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Algiers,2024,5,9
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,2024-05-16 10:45:00,6.3,Light Drizzle,11.9,215,...,03:31,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Andorra,2024,5,10
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,2024-05-16 09:45:00,26.0,Partly Cloudy,13.0,150,...,00:38,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Luanda,2024,5,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,2026-04-12 02:30:00,19.1,Partly Cloudy,3.6,178,...,14:31,Waning Crescent,31,2026-04-12,02:30:00,America,Caracas,2026,4,2
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,2026-04-12 13:30:00,34.2,Sunny,11.2,245,...,13:21,Waning Crescent,35,2026-04-12,13:30:00,Asia,Bangkok,2026,4,13
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,2026-04-12 09:30:00,19.3,Sunny,6.5,217,...,13:45,Waning Crescent,34,2026-04-12,09:30:00,Asia,Aden,2026,4,9
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,2026-04-12 08:30:00,18.5,Sunny,13.7,90,...,14:30,Waning Crescent,33,2026-04-12,08:30:00,Africa,Lusaka,2026,4,8
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,2026-04-12 08:30:00,17.4,Sunny,7.9,43,...,14:22,Waning Crescent,33,2026-04-12,08:30:00,Africa,Harare,2026,4,8

#### 7. Reset index

In [108]:
df = df.reset_index(drop=True)

In [109]:
df

,country,location_name,latitude,longitude,timezone,last_updated,temperature_celsius,condition_text,wind_kph,wind_degree,...,moonset,moon_phase,moon_illumination,date,time,continent,city,year,month,hour
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,338,...,01:11,Waxing Gibbous,55,2024-05-16,13:15:00,Asia,Kabul,2024,5,13
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,2024-05-16 10:45:00,19.0,Partly Cloudy,11.2,320,...,02:14,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Tirane,2024,5,10
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,2024-05-16 09:45:00,23.0,Sunny,15.1,280,...,02:14,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Algiers,2024,5,9
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,2024-05-16 10:45:00,6.3,Light Drizzle,11.9,215,...,03:31,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Andorra,2024,5,10
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,2024-05-16 09:45:00,26.0,Partly Cloudy,13.0,150,...,00:38,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Luanda,2024,5,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135058,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,2026-04-12 02:30:00,19.1,Partly Cloudy,3.6,178,...,14:31,Waning Crescent,31,2026-04-12,02:30:00,America,Caracas,2026,4,2
135059,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,2026-04-12 13:30:00,34.2,Sunny,11.2,245,...,13:21,Waning Crescent,35,2026-04-12,13:30:00,Asia,Bangkok,2026,4,13
135060,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,2026-04-12 09:30:00,19.3,Sunny,6.5,217,...,13:45,Waning Crescent,34,2026-04-12,09:30:00,Asia,Aden,2026,4,9
135061,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,2026-04-12 08:30:00,18.5,Sunny,13.7,90,...,14:30,Waning Crescent,33,2026-04-12,08:30:00,Africa,Lusaka,2026,4,8
135062,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,2026-04-12 08:30:00,17.4,Sunny,7.9,43,...,14:22,Waning Crescent,33,2026-04-12,08:30:00,Africa,Harare,2026,4,8

# REMOVE

In [110]:
df.rename(columns={
    'location_name': 'location',
    
    'air_quality_Carbon_Monoxide': 'co',
    'air_quality_Ozone': 'ozone',
    'air_quality_Nitrogen_dioxide': 'no2',
    'air_quality_Sulphur_dioxide': 'so2',
    'air_quality_PM2.5': 'pm2.5',
    'air_quality_PM10': 'pm10',

    
},inplace=True)

# 8. Save cleaned data

In [111]:
df

,country,location,latitude,longitude,timezone,last_updated,temperature_celsius,condition_text,wind_kph,wind_degree,...,moonset,moon_phase,moon_illumination,date,time,continent,city,year,month,hour
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,338,...,01:11,Waxing Gibbous,55,2024-05-16,13:15:00,Asia,Kabul,2024,5,13
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,2024-05-16 10:45:00,19.0,Partly Cloudy,11.2,320,...,02:14,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Tirane,2024,5,10
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,2024-05-16 09:45:00,23.0,Sunny,15.1,280,...,02:14,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Algiers,2024,5,9
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,2024-05-16 10:45:00,6.3,Light Drizzle,11.9,215,...,03:31,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Andorra,2024,5,10
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,2024-05-16 09:45:00,26.0,Partly Cloudy,13.0,150,...,00:38,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Luanda,2024,5,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135058,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,2026-04-12 02:30:00,19.1,Partly Cloudy,3.6,178,...,14:31,Waning Crescent,31,2026-04-12,02:30:00,America,Caracas,2026,4,2
135059,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,2026-04-12 13:30:00,34.2,Sunny,11.2,245,...,13:21,Waning Crescent,35,2026-04-12,13:30:00,Asia,Bangkok,2026,4,13
135060,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,2026-04-12 09:30:00,19.3,Sunny,6.5,217,...,13:45,Waning Crescent,34,2026-04-12,09:30:00,Asia,Aden,2026,4,9
135061,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,2026-04-12 08:30:00,18.5,Sunny,13.7,90,...,14:30,Waning Crescent,33,2026-04-12,08:30:00,Africa,Lusaka,2026,4,8
135062,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,2026-04-12 08:30:00,17.4,Sunny,7.9,43,...,14:22,Waning Crescent,33,2026-04-12,08:30:00,Africa,Harare,2026,4,8

In [112]:
df.columns

Index(['country', 'location', 'latitude', 'longitude', 'timezone',
       'last_updated', 'temperature_celsius', 'condition_text', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'precip_mm', 'humidity',
       'cloud', 'feels_like_celsius', 'visibility_km', 'uv_index', 'gust_kph',
       'co', 'ozone', 'no2', 'so2', 'pm2.5', 'pm10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunset',
       'moonrise', 'moonset', 'moon_phase', 'moon_illumination', 'date',
       'time', 'continent', 'city', 'year', 'month', 'hour'],
      dtype='object')

In [113]:
df.to_csv("Cleaned_Weather.csv", index=False)

print("Cleaning Completed")
print(df.info())

Cleaning Completed
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135063 entries, 0 to 135062
Data columns (total 39 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   country                     135063 non-null  object
 1   location                    135063 non-null  object
 2   latitude                    135063 non-null  float64
 3   longitude                   135063 non-null  float64
 4   timezone                    135063 non-null  object
 5   last_updated                135063 non-null  datetime64[ns]
 6   temperature_celsius         135063 non-null  float64
 7   condition_text              135063 non-null  object
 8   wind_kph                    135063 non-null  float64
 9   wind_degree                 135063 non-null  int64
 10  wind_direction              135063 non-null  object
 11  pressure_mb                 135063 non-null  int64
 12  precip_mm                   135063 non-null  float64
 13  humidity                    135063 non-null  int64
 14  cloud                       135063 non-null  int64
 15  feels_like_celsius          135063 non-null  float64
 16  visibility_km               135063 non-null  float64
 17  uv_index                    135063 non-null  float64
 18  gust_kph                    135063 non-null  float64
 19  co                          135063 non-null  float64
 20  ozone                       135063 non-null  float64
 21  no2                         135063 non-null  float64
 22  so2                         135063 non-null  float64
 23  pm2.5                       135063 non-null  float64
 24  pm10                        135063 non-null  float64
 25  air_quality_us-epa-index    135063 non-null  int64
 26  air_quality_gb-defra-index  135063 non-null  int64
 27  sunset                      135063 non-null  object
 28  moonrise                    135063 non-null  object
 29  moonset                     135063 non-null  object
 30  moon_phase                  135063 non-null  object
 31  moon_illumination           135063 non-null  int64
 32  date                        135063 non-null  object
 33  time                        135063 non-null  object
 34  continent                   135063 non-null  object
 35  city                        135063 non-null  object
 36  year                        135063 non-null  int32
 37  month                       135063 non-null  int32
 38  hour                        135063 non-null  int32
dtypes: datetime64[ns](1), float64(15), int32(3), int64(7), object(13)
memory usage: 38.6+ MB
None

In [114]:
df.dtypes

country                               object
location                              object
latitude                             float64
longitude                            float64
timezone                              object
last_updated                  datetime64[ns]
temperature_celsius                  float64
condition_text                        object
wind_kph                             float64
wind_degree                            int64
wind_direction                        object
pressure_mb                            int64
precip_mm                            float64
humidity                               int64
cloud                                  int64
feels_like_celsius                   float64
visibility_km                        float64
uv_index                             float64
gust_kph                             float64
co                                   float64
ozone                                float64
no2                                  float64
so2                                  float64
pm2.5                                float64
pm10                                 float64
air_quality_us-epa-index               int64
air_quality_gb-defra-index             int64
sunset                                object
moonrise                              object
moonset                               object
moon_phase                            object
moon_illumination                      int64
date                                  object
time                                  object
continent                             object
city                                  object
year                                   int32
month                                  int32
hour                                   int32
dtype: object

In [118]:
df.to_csv("Cleaned_Weather.csv", index=False)

In [119]:
df

,country,location,latitude,longitude,timezone,last_updated,temperature_celsius,condition_text,wind_kph,wind_degree,...,moonset,moon_phase,moon_illumination,date,time,continent,city,year,month,hour
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,338,...,01:11,Waxing Gibbous,55,2024-05-16,13:15:00,Asia,Kabul,2024,5,13
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,2024-05-16 10:45:00,19.0,Partly Cloudy,11.2,320,...,02:14,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Tirane,2024,5,10
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,2024-05-16 09:45:00,23.0,Sunny,15.1,280,...,02:14,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Algiers,2024,5,9
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,2024-05-16 10:45:00,6.3,Light Drizzle,11.9,215,...,03:31,Waxing Gibbous,55,2024-05-16,10:45:00,Europe,Andorra,2024,5,10
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,2024-05-16 09:45:00,26.0,Partly Cloudy,13.0,150,...,00:38,Waxing Gibbous,55,2024-05-16,09:45:00,Africa,Luanda,2024,5,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135058,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,2026-04-12 02:30:00,19.1,Partly Cloudy,3.6,178,...,14:31,Waning Crescent,31,2026-04-12,02:30:00,America,Caracas,2026,4,2
135059,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,2026-04-12 13:30:00,34.2,Sunny,11.2,245,...,13:21,Waning Crescent,35,2026-04-12,13:30:00,Asia,Bangkok,2026,4,13
135060,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,2026-04-12 09:30:00,19.3,Sunny,6.5,217,...,13:45,Waning Crescent,34,2026-04-12,09:30:00,Asia,Aden,2026,4,9
135061,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,2026-04-12 08:30:00,18.5,Sunny,13.7,90,...,14:30,Waning Crescent,33,2026-04-12,08:30:00,Africa,Lusaka,2026,4,8
135062,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,2026-04-12 08:30:00,17.4,Sunny,7.9,43,...,14:22,Waning Crescent,33,2026-04-12,08:30:00,Africa,Harare,2026,4,8